Repository wecode-bootcamp-korea/36-1st-Usopp-frontend, pull requests merged in 2022-08, with the labels that each got.

#2 [36기 소재현]ADD: nav-bar 구현완료 리뷰반영완료
  README.md
  public/image/1.jpg
  public/image/body.jpg
  public/image/book.jpg
  public/image/home.jpg
  public/image/search.webp
  public/image/shampoo.jpg
  public/image/skin.jpg
  public/image/test.png
  public/image/travel.jpg
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavBarCategori/Categorie.js
  src/Components/Nav/NavBarCategori/Categorie.scss
  src/Components/Nav/NavBarData/NavBarData.js
  src/styles/variable.scss
Labels: 멘토 리뷰 요청

#7 [36기 김준호]ADD: footer UI 구현
  public/index.html
  src/Components/Footer/FOOTER_DATA.js
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/FooterBlock/FooterBlock.js
  src/Router.js
Labels: 완료

#5 [36기 소재현]ADD:상세페이지UI구현
  package-lock.json
  package.json
  public/data/Perfume.json
  public/image/test.webp
  src/Router.js
  src/pages/Product/Perfume.js
  src/pages/Product/Perfume.scss
  src/pages/Product/ProductPerfume.js
  src/pages/Product/ProductPerfume.scss
Labels: 멘토 리뷰 요청

#4 [36기 김준호]ADD: 장바구니 UI 구현
  public/data/data.json
  public/data/data1.json
  public/index.html
  src/Components/Cart/Cart.js
  src/Components/Cart/Cart.scss
  src/Components/Cart/Product/Product.js
  src/Components/Cart/Product/Product.scss
  src/Router.js
Labels: Conflict 해결 요청

#8 제품 페이지 통신 완료
  public/data/data.json
  src/Components/Cart/Cart.js
  src/Components/Cart/Product/Product.js
  src/Components/Nav/Nav.js
  src/Components/Nav/NavBarCategori/Categorie.js
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/DetailList.js
  src/pages/Main/DetailList.scss
  src/pages/Main/Main.js
  src/pages/Main/Proudct.js
  src/pages/Main/SubProudct.js
  src/pages/Product/ProductPerfume.js
Labels: 완료
